### ISSUE TITLE
Is it a concern about the seek-bzip dependency with LGPL license?

### ISSUE THREAD

**Issue by raymondfeng** [kevva/decompress-tarbz2#2]
`npm ls` finds a dependency on seek-bzip which is LGPL licensed . See https://github.com/cscott/seek-bzip/blob/master/package.json#L11. 

Is it a concern of decompress-tarbz2 under MIT?

See https://github.com/yeoman/generator/issues/830

**Comment by kevva** [comment]
Lets keep the discussion in yeoman/generator#830.

**Comment by cscott** [comment]
FWIW `seek-bzip` has been relicensed to MIT.
