### ISSUE TITLE
consider streaming api

### ISSUE THREAD

**Issue by juliangruber** [kevva/decompress-tarbz2#4]
I have a problem with a tbz that doesn't fit into memory, hence it would need to be decompressed in a streaming manner. do you have plans to support this?

**Comment by kevva** [comment]
Might be able to accept a stream, though I'll need to make sure it works in harmony with the promise API.

**Comment by kevva** [comment]
So I think we can do this, see https://github.com/kevva/decompress-tar/pull/7.

**Comment by juliangruber** [comment]
that looks great, I'm curious though how you'd implement the bzip part with a stream

**Comment by kevva** [comment]
See the PR in #5.
